# Generated by Django 3.2.18 on 2023-03-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='new',
            field=models.TextField(default='None'),
        ),
    ]
